branches:
  only:
  - master

skip_non_tags: true

build: off
test: off

environment:
  matrix:
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.8"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.8"
      PYTHON_ARCH: "64"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "%PYTHON%/Scripts/pip.exe install pyinstaller"

test_script:
  - "echo test"
  
after_test:
  - "%PYTHON%/Scripts/pyinstaller.exe -w -F -n painter-%PYTHON_ARCH%bits.exe painter.py"
  
artifacts:
  - path: "dist/painter-%PYTHON_ARCH%bits.exe"
    name: painter

deploy:
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: 9AXBVcFsLwmlIqRtE1Iiocs1T5pEvXTryofJpx8nlLCzmFfSI8gp7u6FabwSRIDI  # your encrypted token from GitHub
  artifact: painter
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only
